CREATE DATABASE DB_TIETA_PERFUMARIA;
USE DB_TIETA_PERFUMARIA;

CREATE TABLE TB_CLIENTE(
	CD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
	NM_CLIENTE VARCHAR(255) NOT NULL,
	DS_EMAIL VARCHAR(255) NOT NULL,
    ST_ADMIN Boolean NOT NULL
);

CREATE TABLE TB_PRODUTOS(
	CD_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
	NM_PRODUTO VARCHAR(255) NOT NULL, 
	VL_PRODUTO INT NOT NULL
);

CREATE TABLE TB_CLIENTE_PRODUTO(
	CD_CLIENTE_PRODUTO INT AUTO_INCREMENT PRIMARY KEY, 
	ID_PRODUTO INT,
	ID_CLIENTE INT
);

CREATE TABLE TB_CARRINHO(
	CD_CARRINHO INT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENTE_PRODUTO INT
);

CREATE TABLE TB_CONTATO(
	CD_CONTATO INT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENTE INT
);

CREATE TABLE TB_IMG(
	CD_IMG INT AUTO_INCREMENT PRIMARY KEY,
	NM_IMG VARCHAR(255) NOT NULL,
	DS_IMG VARCHAR(255) NOT NULL,
    DS_CATEGORY_IMG VARCHAR(255) NOT NULL
);

ALTER TABLE TB_CLIENTE_PRODUTO ADD	
FOREIGN KEY CHAVE_ESTRANGEIRA_PRODUTO (ID_PRODUTO) REFERENCES TB_PRODUTOS (CD_PRODUTO);

ALTER TABLE TB_CLIENTE_PRODUTO ADD	
FOREIGN KEY CHAVE_ESTRANGEIRA_CLIENTE (ID_CLIENTE) REFERENCES TB_CLIENTE (CD_CLIENTE);

ALTER TABLE TB_CARRINHO ADD	
FOREIGN KEY CHAVE_ESTRANGEIRA_CLIENTE_PRODUTO (ID_CLIENTE_PRODUTO) REFERENCES TB_CLIENTE_PRODUTO (CD_CLIENTE_PRODUTO);

ALTER TABLE TB_CONTATO ADD
FOREIGN KEY CHAVE_ESTRANGEIRA_CONTATOS_CLIENTES (ID_CLIENTE) REFERENCES TB_CLIENTE (CD_CLIENTE);