CREATE DATABASE DB_TIETA_PERFUMARIA;
USE DB_TIETA_PERFUMARIA;
CREATE TABLE TB_CLIENTE(
	CD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
	NM_CLIENTE VARCHAR(255) NOT NULL,
	DS_EMAIL VARCHAR(255) NOT NULL
);
CREATE TABLE TB_PRODUTOS(
	CD_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
	NM_PRODUTO VARCHAR(255) NOT NULL, 
	VL_PRODUTO INT NOT NULL
);
CREATE TABLE TB_CLIENTE_PRODUTO(
	CD_CLIENTE_PRODUTO INT AUTO_INCREMENT PRIMARY KEY, 
	ID_PRODUTO INT,
	ID_CLIENTE INT
);
CREATE TABLE TB_CARRINHO(
	CD_CARRINHO INT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENTE_PRODUTO INT
);
