CREATE DATABASE DB_TIETA_PERFUMARIA;
USE DB_TIETA_PERFUMARIA;
CREATE TABLE TB_CLIENTS(
	CD_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
	DS_CLIENT_USER VARCHAR(255) NOT NULL,
	DS_CLIENT_EMAIL VARCHAR(255) NOT NULL,
	DS_CLIENT_PASSWORD VARCHAR(255) NOT NULL,
	ST_CLIENT_ADMIN BOOLEAN NOT NULL,
	NM_CLIENT VARCHAR(255) NOT NULL,
	DS_CLIENT_BIRTHDATE DATE NOT NULL,
    DS_CLIENT_CPF VARCHAR(255) NOT NULL,
    DS_CLIENT_PHONE VARCHAR(255) NOT NULL,
    ID_ADDRESS INT,
    ID_DS_IMG INT
);
CREATE TABLE TB_ADDRESS(
	CD_ADDRESS INT AUTO_INCREMENT PRIMARY KEY, 
    DS_ADDRESS_STREET VARCHAR(255) NOT NULL,
    DS_ADDRESS_NEIGHBORHOOD VARCHAR(255) NOT NULL,
    DS_ADDRESS_CITY VARCHAR(255) NOT NULL,
    DS_ADDRESS_STATE VARCHAR(255) NOT NULL,
    DS_ADDRESS_COMPLEMENT VARCHAR(255),
    DS_ADDRESS_ZIPCODE VARCHAR(9) NOT NULL
);
CREATE TABLE TB_PRODUCTS(
	CD_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
	NM_PRODUCT VARCHAR(255) NOT NULL,
	DS_PRODUCT LONGTEXT,
	ID_DS_IMG INT,
	VL_PRODUCT INT NOT NULL
);
CREATE TABLE TB_CLIENTS_PRODUCTS(
	CD_CLIENT_PRODUCT INT AUTO_INCREMENT PRIMARY KEY, 
	ID_CLIENT INT,
    ID_PRODUCT INT
);
CREATE TABLE TB_BASKETS(
	CD_BASKET INT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENT_PRODUCT INT
);
CREATE TABLE TB_IMGS(
	CD_IMG INT AUTO_INCREMENT PRIMARY KEY,
	NM_IMG VARCHAR(255) NOT NULL,
	DS_IMG VARCHAR(255) NOT NULL,
    DS_CATEGORY_IMG VARCHAR(255) NOT NULL
);
ALTER TABLE TB_CLIENTS ADD FOREIGN KEY (ID_ADDRESS) REFERENCES TB_ADDRESS (CD_ADDRESS);
ALTER TABLE TB_CLIENTS_PRODUCTS ADD FOREIGN KEY (ID_CLIENT) REFERENCES TB_CLIENTS (CD_CLIENT);
ALTER TABLE TB_CLIENTS_PRODUCTS ADD	FOREIGN KEY (ID_PRODUCT) REFERENCES TB_PRODUCTS (CD_PRODUCT);
ALTER TABLE TB_BASKETS ADD FOREIGN KEY (ID_CLIENT_PRODUCT) REFERENCES TB_CLIENTS_PRODUCTS (CD_CLIENT_PRODUCT);
/*ALTER TABLE TB_CLIENTS ADD FOREIGN KEY (ID_DS_IMG) REFERENCES TB_IMGS (CD_IMG);*/
INSERT INTO TB_ADDRESS VALUES (NULL, 'rua', 'bairro', 'cidade', 'estado', 'complemento', '00000-000');
INSERT INTO TB_CLIENTS VALUES ( NULL, 'admin', 'admin@admin.com', 'admin', 1, 'Administrator', '2002-02-20', '000.000.000-00', '(00) 00000-0000', 1, 1);
/*SELECT * FROM TB_CLIENTS;*/