DROP DATABASE IF EXISTS DB_TIETA_PERFUMARIA;
CREATE DATABASE IF NOT EXISTS DB_TIETA_PERFUMARIA;
USE DB_TIETA_PERFUMARIA;
CREATE TABLE IF NOT EXISTS TB_CLIENTS(
	CD_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
	DS_CLIENT_USER VARCHAR(255) NOT NULL,
	DS_CLIENT_EMAIL VARCHAR(255) NOT NULL,
	DS_CLIENT_PASSWORD VARCHAR(255) NOT NULL,
	ST_CLIENT_ADMIN BOOLEAN NOT NULL,
	NM_CLIENT VARCHAR(255) NOT NULL,
	DS_CLIENT_BIRTHDATE VARCHAR(255) NOT NULL,
    DS_CLIENT_CPF VARCHAR(255) NOT NULL,
    DS_CLIENT_PHONE VARCHAR(255) NOT NULL,
    ID_ADDRESS INT NOT NULL,
    ID_CLIENT_IMG INT NOT NULL
);
CREATE TABLE IF NOT EXISTS TB_ADDRESS(
	CD_ADDRESS INT AUTO_INCREMENT PRIMARY KEY,
    DS_ADDRESS_STREET VARCHAR(255) NOT NULL,
    DS_ADDRESS_NEIGHBORHOOD VARCHAR(255) NOT NULL,
    DS_ADDRESS_CITY VARCHAR(255) NOT NULL,
    DS_ADDRESS_STATE VARCHAR(255) NOT NULL,
    DS_ADDRESS_COMPLEMENT VARCHAR(255),
    DS_ADDRESS_ZIPCODE VARCHAR(9) NOT NULL
);
CREATE TABLE IF NOT EXISTS TB_PRODUCTS(
	CD_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
	NM_PRODUCT VARCHAR(255) NOT NULL,
	DS_PRODUCT LONGTEXT,
	VL_PRODUCT INT NOT NULL,
    ID_PRODUCT_CATEGORY INT,
    ID_PRODUCT_IMG INT
);
CREATE TABLE IF NOT EXISTS TB_PRODUCTS_CATEGORIES(
	CD_PRODUCT_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NM_PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
    DS_PRODUCT_CATEGORY LONGTEXT
);
CREATE TABLE IF NOT EXISTS TB_CLIENTS_PRODUCTS(
	CD_CLIENT_PRODUCT INT AUTO_INCREMENT PRIMARY KEY, 
	ID_CLIENT INT,
    ID_PRODUCT INT
);
CREATE TABLE IF NOT EXISTS TB_BASKETS(
	CD_BASKET INT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENT_PRODUCT INT
);
CREATE TABLE IF NOT EXISTS TB_CLIENTS_IMGS(
	CD_CLIENT_IMG INT AUTO_INCREMENT PRIMARY KEY,
	DS_CLIENT_IMG VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS TB_PRODUCTS_IMGS(
	CD_PRODUCT_IMG INT AUTO_INCREMENT PRIMARY KEY,
	DS_PRODUCT_IMG VARCHAR(255) NOT NULL
);
ALTER TABLE TB_CLIENTS ADD FOREIGN KEY (ID_ADDRESS) REFERENCES TB_ADDRESS (CD_ADDRESS);
ALTER TABLE TB_CLIENTS_PRODUCTS ADD FOREIGN KEY (ID_CLIENT) REFERENCES TB_CLIENTS (CD_CLIENT);
ALTER TABLE TB_CLIENTS_PRODUCTS ADD	FOREIGN KEY (ID_PRODUCT) REFERENCES TB_PRODUCTS (CD_PRODUCT);
ALTER TABLE TB_BASKETS ADD FOREIGN KEY (ID_CLIENT_PRODUCT) REFERENCES TB_CLIENTS_PRODUCTS (CD_CLIENT_PRODUCT);
ALTER TABLE TB_CLIENTS ADD FOREIGN KEY (ID_CLIENT_IMG) REFERENCES TB_CLIENTS_IMGS (CD_CLIENT_IMG);
ALTER TABLE TB_PRODUCTS ADD FOREIGN KEY (ID_PRODUCT_CATEGORY) REFERENCES TB_PRODUCTS_CATEGORIES (CD_PRODUCT_CATEGORY);
ALTER TABLE TB_PRODUCTS ADD FOREIGN KEY (ID_PRODUCT_IMG) REFERENCES TB_PRODUCTS_IMGS (CD_PRODUCT_IMG);
INSERT INTO TB_CLIENTS_IMGS VALUES (NULL, '/img/avatars/avatar.png');
INSERT INTO TB_ADDRESS VALUES (NULL, 'rua do admin', 'bairro do admin', 'cidade do admin', 'estado do admin', 'complemento do admin', '00000-000');
INSERT INTO TB_CLIENTS VALUES (NULL, 'admin', 'admin@admin.com', '$2y$10$HAep5zcsfr7ewMT4j.1NHO81XqZCw01iSxUAkhfm.5uKAjdV9f3we', '1', 'Administrador', '0000-00-00', '000.000.000-00', '(11) 11111-1111', 1, 1);
INSERT INTO TB_CLIENTS_IMGS VALUES (NULL, '/img/avatars/avatar2.png');
INSERT INTO TB_ADDRESS VALUES (NULL, 'rua do user', 'bairro do user', 'cidade do user', 'estado do user', 'complemento do user', '11111-111');
INSERT INTO TB_CLIENTS VALUES (NULL, 'user', 'user@user.com', '$2y$10$VnEcALY9dgBiRa5b6QsPteT6WdPKmh4j6WlhERN0y4HvwhPqqglUS', '0', 'Usuario', '1111-11-11', '111.111.111-11', '(00) 00000-0000', 2, 2);
INSERT INTO TB_PRODUCTS_IMGS VALUES (NULL, '/img/products/product.png');
INSERT INTO TB_PRODUCTS_CATEGORIES VALUES (NULL, 'Nome da categoria' , 'Descrição da categoria');
INSERT INTO TB_PRODUCTS VALUES (NULL,'Nome do produto' ,'Descrição do produto' , 99, 1, 1);

SELECT * FROM TB_CLIENTS_IMGS;
SELECT * FROM TB_ADDRESS;
SELECT * FROM TB_CLIENTS;
SELECT * FROM TB_PRODUCTS_IMGS;
SELECT * FROM TB_PRODUCTS_CATEGORIES;
SELECT * FROM TB_PRODUCTS;
SELECT P.*, C.*, I.* FROM TB_PRODUCTS AS P INNER JOIN TB_PRODUCTS_CATEGORIES AS C INNER JOIN TB_PRODUCTS_IMGS AS I ON P.ID_PRODUCT_CATEGORY=C.CD_PRODUCT_CATEGORY AND P.ID_PRODUCT_IMG=I.CD_PRODUCT_IMG WHERE CD_PRODUCT = 1;